server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://122.51.60.92:3306/inyaa?useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: helloblog
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true